name: Test self hosted on azure


on:
    workflow_dispatch: 

jobs:
    build:
        runs-on: project-alpha
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Echo
              run: echo 'hello from self-hosted'
            